services:

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "8000"

    env_file:
      - ./.env

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16

    restart: unless-stopped

    environment:
      POSTGRES_USER: stepify
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stepify

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stepify -d stepify"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data: