server {
    listen 80;

    root /usr/share/nginx/html;

    index index.html;

    location /api/ {
        proxy_pass http://backend:8000;
    }

#     location / {
#         try_files $uri $uri/ /index.html;
#     }
# }


# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         root   /usr/share/nginx/html;
#         index  index.html index.htm;
#         try_files $uri $uri/ /index.html;
#     }

    # 💡 追加・修正：静的ファイルは直接配信し、無ければ 404 を返す
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
    }
}